import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ca_tools, CAToolsWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Docker currently serves HTTP directly on the loopback interface.
config :ca_tools, CAToolsWeb.Endpoint, force_ssl: false

# SMTP does not need an HTTP API client.
config :swoosh, api_client: false

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :ca_tools, :secure_cookies, false
